"""empty message

Revision ID: 2d8899c7b0c4
Revises: 8dff8de42317
Create Date: 2019-01-21 14:49:13.622031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8899c7b0c4'
down_revision = '8dff8de42317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
