"""empty message

Revision ID: 38bc0870aa8f
Revises: 2d8899c7b0c4
Create Date: 2019-01-22 17:25:28.424067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bc0870aa8f'
down_revision = '2d8899c7b0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('role', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'role')
    # ### end Alembic commands ###
