"""empty message

Revision ID: 5cd7480d173d
Revises: 38bc0870aa8f
Create Date: 2019-01-25 16:49:51.656737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cd7480d173d'
down_revision = '38bc0870aa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('followed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed'], ['accounts.user_id'], ),
    sa.ForeignKeyConstraint(['follower'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('followed_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['accounts.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('miniblogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('comment_content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['miniblogs.blog_id'], ),
    sa.ForeignKeyConstraint(['commenter_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('pictures',
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('picture_link', sa.String(length=128), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['miniblogs.blog_id'], ),
    sa.PrimaryKeyConstraint('picture_id')
    )
    op.add_column('accounts', sa.Column('avatar_link', sa.String(length=128), nullable=True))
    op.add_column('accounts', sa.Column('signed', sa.String(length=64), nullable=True))
    op.alter_column('accounts', 'password',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'password',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('accounts', 'signed')
    op.drop_column('accounts', 'avatar_link')
    op.drop_table('pictures')
    op.drop_table('comments')
    op.drop_table('miniblogs')
    op.drop_table('messages')
    op.drop_table('follows')
    # ### end Alembic commands ###
