"""empty message

Revision ID: 6c0f3e824412
Revises: 5cd7480d173d
Create Date: 2019-01-31 17:43:48.292329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c0f3e824412'
down_revision = '5cd7480d173d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.drop_constraint('follows_ibfk_2', 'follows', type_='foreignkey')
    op.drop_constraint('follows_ibfk_1', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'accounts', ['follower_id'], ['user_id'])
    op.create_foreign_key(None, 'follows', 'accounts', ['followed_id'], ['user_id'])
    op.drop_column('follows', 'followed')
    op.drop_column('follows', 'follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('follower', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('follows', sa.Column('followed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_ibfk_1', 'follows', 'accounts', ['followed'], ['user_id'])
    op.create_foreign_key('follows_ibfk_2', 'follows', 'accounts', ['follower'], ['user_id'])
    op.drop_column('follows', 'follower_id')
    # ### end Alembic commands ###
