"""empty message

Revision ID: 8e785e8691ae
Revises: 
Create Date: 2019-04-15 18:55:13.770672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e785e8691ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('signed', sa.String(length=64), nullable=True),
    sa.Column('avatar_link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_accounts_account'), 'accounts', ['account'], unique=True)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['accounts.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['accounts.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('miniblogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('DisableComments', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('comment_content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['miniblogs.blog_id'], ),
    sa.ForeignKeyConstraint(['commenter_id'], ['accounts.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('pictures',
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('picture_link', sa.String(length=128), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['miniblogs.blog_id'], ),
    sa.PrimaryKeyConstraint('picture_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('comments')
    op.drop_table('miniblogs')
    op.drop_table('messages')
    op.drop_table('follows')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
